# washington/config.yaml

# Tell Snakemake which build(s) to run
builds:
  - washington

# Auspice export settings (override defaults)
export:
  auspice_config: washington/auspice_config.json
  description: washington/description.md
  lat_longs: ../defaults/lat_longs.tsv

# Color schemes (used for Auspice visualization)
colors:
  color_schemes: ../defaults/color_schemes.tsv
  color_orderings: ../defaults/color_orderings.tsv

# Subsampling (points to WA-specific scheme)
subsampling:
  washington: washington/subsampling.yaml

strain_id_field: "accession"
reference: "reference.gb"
# ---- Per-build settings (IMPORTANT: strings, not nested dicts) ----
# Filter: CLI flags appended to augur filter
filter:
  # Where the workflow looks for per-build include/exclude lists
  include: "../defaults/north-america/include.txt"
  exclude: "../defaults/north-america/exclude.txt"

  # Per-build “specific” flags are strings indexed by build name
  #HAVE to have subsample max
filter:
  specific:
    washington: >-
      --subsample-max-sequences 99999
      --min-date 2006
      --query "region=='North America' & (MuV_genotype=='G')"

# Traits: space-separated column names, as a single string
traits:
  washington: "country division MuV_genotype MuV_genotype_nextclade_sh MuV_genotype_nextclade_genome"
  sampling_bias_correction: 2.5

# Refine: CLI flags as a single string
refine:
  washington: "--clock-filter-iqd 4 --date-inference marginal"

# Ancestral: a simple string in this repo
ancestral:
  washington: "joint"

# Translate: not used here, keep empty string
translate:
  washington: ""

# Tip frequencies (temporal trends)
tip_frequencies:
  washington:
    min_date: 2006
    interval: 3
      # Quarterly narrow_bandwidth or every 3 months (3 /12.0 = 0.25)
    narrow_bandwidth: 0.25
    proportion_wide: 0.0
